stages:
  - build
  - deploy

build:
  stage: build
  image: musicscience37/sphinx-doxygen:v-2.1
  script:
    - make html
  artifacts:
    paths:
      - build
    expire_in: '1 week'

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
    - public
  only:
    - master
