stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:latest-python-3.10

pre-commit:
  stage: test
  image: musicscience37/sphinx-doxygen
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    key:
      prefix: poetry-linux
      files:
        - poetry.lock
    paths:
      - .venv
  needs: []

build:
  stage: build
  image: musicscience37/sphinx-doxygen
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run make html
  cache:
    key:
      prefix: poetry-linux
      files:
        - poetry.lock
    paths:
      - .venv
  artifacts:
    paths:
      - build
    expire_in: "1 week"
  needs: []

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - master
  needs: [build]
