image: musicscience37/sphinx:version-2.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip3 install -r requirements.txt
    - make html
  artifacts:
    paths:
      - build
    expire_in: '1 week'

pages:
  stage: deploy
  script:
    - mv build/html public
  artifacts:
    paths:
    - public
  only:
    - master
