stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/musicscience37_ci/sphinx-doxygen-docker:v1-1
  script:
    - pip3 install -r requirements.txt
    - make html
  artifacts:
    paths:
      - build
    expire_in: '1 week'

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
    - public
  only:
    - master
