stages:
  - test
  - build
  - deploy

image: musicscience37/sphinx-doxygen:v-3.2

include:
  - template: Dependency-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:2-python-3.9

pre-commit:
  stage: test
  script:
    - pipenv sync --dev
    - pipenv run pre-commit run --all-files

build:
  stage: build
  script:
    - apt update
    - apt install -y fonts-ipafont
    - pipenv sync
    - pipenv run make html
  artifacts:
    paths:
      - build
    expire_in: "1 week"

pages:
  stage: deploy
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - master
