stages:
  - build
  - deploy

build:
  stage: build
  image: musicscience37/sphinx-doxygen:v-3.0
  script:
    - pipenv sync
    - pipenv run make html
  artifacts:
    paths:
      - build
    expire_in: '1 week'
  cache:
    key:
      files:
        - Pipfile.lock
    paths:
      - .venv/

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
    - public
  only:
    - master
