stages:
  - test # このステージの名前は include している設定で使用されるため変更不可
  - build
  - test after build
  - deploy

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  SPHINX_IMAGE: musicscience37/sphinx-doxygen:gcc13

pre-commit:
  stage: test
  needs: []
  image: ${SPHINX_IMAGE}
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry sync
    - poetry run pre-commit run --all-files
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint .
  interruptible: true

build:
  stage: build
  needs: []
  image: ${SPHINX_IMAGE}
  variables:
    PYDEVD_DISABLE_FILE_VALIDATION: 1
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry sync
    - poetry run ./build.sh
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: jupyter-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - build/jupyter_cache
    - key: htmltest before build-${CI_JOB_NAME}
      paths:
        - .htmltest before build
  artifacts:
    paths:
      - build/html
    expire_in: "1 week"

check html:
  stage: test after build
  needs:
    - build
  dependencies:
    - build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install -y curl
    - mkdir -p /usr/local/bin
    - curl https://htmltest.wjdp.uk | bash -s -- -b /usr/local/bin
    - htmltest
  # htmltest は不安定なため、失敗しても残りの処理は続ける。
  allow_failure: true

pages:
  stage: deploy
  needs:
    - build
  dependencies:
    - build
  image: alpine
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - main
