stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:2-python-3.9

pre-commit:
  stage: test
  image: musicscience37/pipenv:focal
  script:
    - mkdir -p .venv
    - pipenv sync --dev
    - pipenv run pre-commit run --all-files
  cache:
    key:
      prefix: pipenv-dev
      files:
        - Pipfile.lock
    paths:
      - .venv
  needs: []

build:
  stage: build
  image: musicscience37/sphinx-doxygen
  script:
    - mkdir -p .venv
    - pipenv sync
    - pipenv run make html
  cache:
    key:
      prefix: pipenv-deploy
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - build
    expire_in: "1 week"
  needs: []

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - master
  needs: [build]
