stages:
  - test
  - build
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:2-python-3.9

build:
  stage: build
  image: musicscience37/sphinx-doxygen:v-3.2
  script:
    - apt update
    - apt install -y fonts-ipafont
    - pipenv sync
    - pipenv run make html
  artifacts:
    paths:
      - build
    expire_in: "1 week"

pages:
  stage: deploy
  image: ubuntu
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - master
