stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug

pre-commit:
  stage: test
  image: musicscience37/sphinx-doxygen
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry env use 3.11
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  needs: []

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
      "**/*.css"
  interruptible: true

build:
  stage: build
  image: musicscience37/sphinx-doxygen
  variables:
    PYDEVD_DISABLE_FILE_VALIDATION: 1
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry env use 3.11
    - poetry install
    - poetry run ./build.sh
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: jupyter-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - build/jupyter_cache
  artifacts:
    paths:
      - build
    expire_in: "1 week"
  needs: []

pages:
  stage: deploy
  image: alpine
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - main
  needs: [build]
